BestBuy/Models/Data/Category.cs
using System;
namespace BestBuy.Models
{
	public class Category
	{
		public int CategoryID { get; set; }
		public string Name { get; set; }
		public int DepartmentID { get; set; }
	}
}

BestBuy/Models/Data/Department.cs
using System;
namespace BestBuy.Models
{
	public class Department
	{
		public int DepartmentID { get; set; }
		public string Name { get; set; }
	}
}

BestBuy/Models/Data/Employee.cs
using System;
namespace BestBuy.Models
{
	public class Employee
	{
		public int EmployeeID { get; set; }
		public string FirstName { get; set; }
		public string? MiddleInitial { get; set; }
		public string LastName { get; set; }
		public string EmailAddress { get; set; }
		public string PhoneNumber { get; set; }
		public string Title { get; set; }
		public DateTime DateOfBirth { get; set; }
	}
}

BestBuy/Models/Data/Product.cs
using System;
using MySql.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
namespace BestBuy.Models
{
    public class Product
	{
		public int ProductID { get; set; }
		public string Name { get; set; }
		public double Price { get; set; }
		public int CategoryID { get; set; }
		public int OnSale { get; set; }
		public int? StockLevel { get; set; }
	}
}

BestBuy/Models/ErrorViewModel.cs
namespace BestBuy.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BestBuy/Models/Globals.cs
using System;
namespace BestBuy.Models
{
	public static class Globals {
		public static int Yes = 1;
		public static int No = 0;
		public static Dictionary<int, string> YesNo = new Dictionary<int, string>()
		{
			{ 0, "No" },
			{ 1, "Yes" }
		};
		public enum YesOrNo
		{
			Yes = 1,
			No = 0
		}
	}

}

BestBuy/Models/HtmlHelpers/SelectHelper.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace BestBuy.Models.HtmlHelpers
{
	public static class OnSaleSelectHelper
	{
		
	}

	public static class OnSaleOptionHelper
	{
		
		
	}
}

BestBuy/Models/InputValidation.cs
using System;
namespace BestBuy.Models
{
	public static class InputValidation
	{
        public static List<string> ValidateChanges(Product product)
        {
            var errorMsgs = new List<string>();
            if (string.IsNullOrWhiteSpace(product.Name))
            {
                errorMsgs.Add("Name cannot be empty");
            }
            if (product.Price < 0)
            {
                errorMsgs.Add("Price must be 0 or greater");
            }
            if (product.StockLevel < 0)
            {
                errorMsgs.Add("Stock level must be 0 or greater");
            }
            return errorMsgs;
        }
    }
}

BestBuy/Models/ViewModels/BaseViewModel.cs
using System;
namespace BestBuy.Models.ViewModels
{
	public class BaseViewModel
	{
		public bool IsError { get; set; }
		public List<string> ErrorMsgs { get; set; }
		public List<string> UserRoles { get; set; }
	}
}

BestBuy/Models/ViewModels/CreateProductViewModel.cs
using System;
namespace BestBuy.Models.ViewModels
{
	public class CreateProductViewModel : BaseViewModel
	{
		public Product Product { get; set; }

		public List<Category> Categories { get; set; }


	}
}

BestBuy/Models/ViewModels/EditProductViewModel.cs
using System;
namespace BestBuy.Models.ViewModels
{
	public class EditProductViewModel : BaseViewModel
	{
		public Product Product { get; set; }
	}
}

BestBuy/Models/ViewModels/ProductViewModel.cs
using System;
namespace BestBuy.Models.ViewModels
{
	public class ProductsListViewModel : BaseViewModel
	{
		public List<Product> Products { get; set; }
		public string SearchTerms { get; set; }
	}
}

BestBuy/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BestBuy.Models;

namespace BestBuy.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BestBuy/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySql.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using BestBuy.Models;
using BestBuy.Models.ViewModels;
using BestBuy.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BestBuy.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IProductRepository repo;

        public InventoryController(IProductRepository repo)
        {
            this.repo = repo;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View("Products", new string(""));
        }

        public async Task<IActionResult> GetAllProducts()
        {
            var vm = new ProductsListViewModel()
            {
                Products = await repo.GetAllProducts(),
                SearchTerms = string.Empty
            };
            return View("ProductsList", vm);
        }

        public async Task<IActionResult> SearchProducts(string searchTerms)
        {
            var vm = new ProductsListViewModel()
            {
                Products = await repo.SearchProducts(searchTerms),
                SearchTerms = searchTerms
            };
            return View("ProductsList", vm);
        }

        public async Task<IActionResult> EditProduct(int id)
        {
            var product = await repo.GetProduct(id);
            return View("EditProduct", product);
        }

        public async Task<IActionResult> UpdateProduct(Product product)
        {
            var errors = InputValidation.ValidateChanges(product);

            if (errors.Count != 0)
            {
                ViewBag.InvalidInput = errors;              
            }
            else {
                try
                {
                    var result = await repo.UpdateProduct(product);
                }
                catch (Exception e)
                {
                    ViewBag.SqlError = e.Message;
                }
            }

            var newProd = await repo.GetProduct(product.ProductID);

            return View("EditProduct", newProd);
        }

        public IActionResult CreateProduct()
        {
            var viewModel = new CreateProductViewModel() {

            };
            return View("CreateProduct", viewModel);
        }

        public async Task<IActionResult> AddProductToDatabase(Product product)
        {
            var errors = InputValidation.ValidateChanges(product);
            if (errors.Count > 0)
            {
                ViewBag.InvalidInput = errors;
                return View("CreateProduct", product);
            }
            var result = await repo.CreateProduct(product);
            return View("GetAllProducts");
        }

        public async Task<IActionResult> DeleteProduct(int id)
        {
            var result = await repo.DeleteProduct(id);
            return RedirectToAction("GetAllProducts");
        }
    }
}

BestBuy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BestBuy/Views/Inventory/CreateProduct.cshtml
@model Product

<h2>Create New Item</h2>

<a asp-action="GetAllProducts"
    asp-controller="Inventory"
    class="btn btn-primary">Return To List</a>

@{
    if (ViewBag.SqlError != null)
    {
        <p class="error-message">Database Error: @ViewBag.SqlError</p>
    }
    if (ViewBag.InvalidInput != null)
    {
        <p class="error-message">Invalid input:</p>
        <ul>
            @foreach (var err in ViewBag.InvalidInput)
            {
                <li>@err</li>
            }
        </ul>
    }
}

<form asp-action="AddProductToDatabase" asp-controller="Inventory" method="post">
    <table class="table">
        <thead>
            <tr>
                <td>Name</td>
                <td>Price</td>
                <td>Stock Level</td>
                <td>Category</td>
                <td>OnSale</td>
            </tr>
        </thead>
        <tbody>
            <tr>

                <td>
                    <input asp-for="Name"
                           type="text"
                           class="form-control" />
                </td>
                <td>
                    <input asp-for="Price"
                           type="number"
                           class="form-control" />
                </td>
                <td>
                    <input asp-for="StockLevel"
                           type="number"
                           class="form-control" />
                </td>
                <td>
                    <select asp-for="CategoryID"
                           type="number"
                           class="form-control" >
                        
                    </select>
                </td>
                <td>
                    <select asp-for="OnSale">
                        <option value="@Globals.No" selected>No</option>
                        <option value="@Globals.Yes">Yes</option>
                    </select>
                </td>
            </tr>
        </tbody>
    </table>

    <input type="submit"
           value="Create"
           class="btn btn-primary"/>
</form>

BestBuy/Views/Inventory/EditProduct.cshtml
@model Product

<h2>Edit Item</h2>

<a asp-action="GetAllProducts"
   asp-controller="Inventory"
   class="btn btn-primary">Return To List</a>

@{
    if (ViewBag.SqlError != null)
    {
        <p class="error-message">Database Error: @ViewBag.SqlError</p>
    }
    if (ViewBag.InvalidInput != null)
    {
        <p class="error-message">Invalid input:</p>
        <ul>
            @foreach(var err in ViewBag.InvalidInput)
            {
                <li>@err</li>
            }
        </ul>
    }
}

<form asp-action="UpdateProduct" asp-controller="Inventory">

    <input asp-for="ProductID" type="hidden" value="@Model.ProductID" />
    <input asp-for="CategoryID" type="hidden" value="@Model.CategoryID"/>

    <table class="table">
        <thead>
            <tr>
                <td>Name</td>
                <td>Price</td>
                <td>Stock Level</td>
                <td>OnSale</td>
            </tr>
        </thead>
        <tbody>
            <tr>

                <td>
                    <input asp-for="Name" type="text" value="@Model.Name" class="form-control" />
                </td>
                <td><input asp-for="Price" type="number" value="@Model.Price" class="form-control" /></td>
                <td><input asp-for="StockLevel" type="number" value="@Model.StockLevel" class="form-control" /></td>
                <td>

                    <select asp-for="OnSale">
                        @for (int i = 0; i < 2; i++)
                        {
                            if (i == Model.OnSale)
                            {
                                <option value="@i" selected>@Globals.YesNo[i]</option>
                            }
                            else
                            {
                                <option value="@i">@Globals.YesNo[i]</option>
                            }
                        }
                    </select>
                </td>
            </tr>
        </tbody>
    </table>
    <input type="submit" value="Update" class="btn btn-primary"/>
</form>
@Html.ActionLink(linkText: "Delete",
                 actionName: "DeleteProduct",
                 controllerName: "Inventory",
                 routeValues: new { id = Model.ProductID },
                 htmlAttributes: new
                 {
                     @class = "btn btn-danger",
                     @onclick = "return confirm('Are you sure?')"
                 })
@*<a asp-action="DeleteProduct"
   asp-controller="Inventory"
   asp-route-id="@Model.ProductID"
   class="btn btn-danger"
   onclick="return confirm('Are you sure?')">Delete</a>*@

BestBuy/Views/Inventory/ProductsList.cshtml
@model BestBuy.Models.ViewModels.ProductsListViewModel

<h1>Products</h1>

<form asp-controller="Inventory"
      asp-action="SearchProducts"
      method="post">
    <input type="text"
           name="searchTerms"
           value="@Model.SearchTerms"/>
    <button type="submit">Search</button>
</form>

<a asp-action="CreateProduct"
   asp-controller="Inventory"
   class="btn btn-primary">New Product</a>

<div class="product-list">
    <table class="table">
        <thead>
            <tr>
                <td>Product Id</td>
                <td>Name</td>
                <td>Price</td>
                <td>Stock Level</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model.Products)
            {
                <tr>
                    <td>@p.ProductID</td>
                    <td>@p.Name</td>
                    <td>@p.Price</td>
                    <td>@p.StockLevel</td>
                    <td>
                        @Html.ActionLink(linkText: "Edit",
                                    actionName: "EditProduct",
                                    controllerName: "Inventory",
                                    routeValues: new
                                    {
                                        id = p.ProductID,
                                    },
                                    htmlAttributes: null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BestBuy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BestBuy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BestBuy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BestBuy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="GetAllProducts">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BestBuy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>